from ic import update_user_profile_image
from shopee_c import update_insta_post_to_product, update_color_size_from_shopee_color_size, update_product_category_from_shopee
# update_user_profile_image()
# update_color_size_from_shopee_color_size()
# update_product_category_from_shopee()
update_insta_post_to_product()
