language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

branches:
  only:
    - master
before_deploy: # 배포하기전 하는 작업들
  - cd app
  - zip -r wachu * # wachu 라는 이름으로 zip 파일 생성
  - mkdir -p deploy # deploy 라는 디렉터리를 만듬
  - mv wachu.zip deploy/wachu.zip # deploy 디렉터리로 wachu.zip 파일을 이동
deploy: # 배포
  - provider: s3 # AWS S3를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: wachu # S3에 생성한 버킷
    region: ap-southeast-1
    skip_cleanup: true
    local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
    wait-until-deployed: true
    on:
      repo: seo-burning/wachu #Github 주소
      branch: master
  - provider: codedeploy # AWS CodeDeploy를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: wachu # AWS CodeDeploy가 다운로드 받은 버킷
    key: wachu.zip # 해당 버킷에 저장되어 있는 파일 이름
    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
    application: dabi-code-deploy # AWS 배포 애플리케이션
    deployment_group: dabi-code-deploy-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-southeast-1
    wait-until-deployed: true
    on:
      repo: seo-burning/wachu
      branch: master
notifications:
  email:
    recipients:
      - su.seo@burningb.com
