# Generated by Django 3.0.6 on 2020-07-15 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0052_store_validation_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0096_auto_20200711_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pick AB / AB 픽',
                'verbose_name_plural': 'Pick AB / AB 픽',
            },
        ),
        migrations.CreateModel(
            name='PickABResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selection', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=2, null=True)),
                ('pick_AB', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pick.PickAB')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
                ('outlink', models.URLField(blank=True, max_length=500, null=True)),
                ('ab_pick_set', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='pick.PickAB')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Age')),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Primary_Style')),
                ('product_category', models.ManyToManyField(blank=True, related_name='product_category_set', to='product.ProductCategory')),
                ('product_color', models.ManyToManyField(blank=True, related_name='product_color_set', to='product.ProductColor')),
                ('secondary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Secondary_Style')),
            ],
            options={
                'verbose_name': 'Pick / 픽',
                'verbose_name_plural': 'Pick / 픽',
            },
        ),
    ]
