# Generated by Django 2.2.3 on 2019-07-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuPickSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date', models.DateField(max_length=30, verbose_name='Section Published Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Age')),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Primary_Style')),
                ('product_category', models.ManyToManyField(blank=True, related_name='product_category_set', to='product.ProductCategory')),
                ('product_color', models.ManyToManyField(blank=True, related_name='product_color_set', to='product.ProductColor')),
                ('secondary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Secondary_Style')),
                ('tpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Tpo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuPickRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('outlink', models.URLField(blank=True, max_length=500, null=True)),
                ('pick_image', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
                ('chu_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pick.ChuPoint')),
                ('pick_set', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_rating_set', to='pick.ChuPickSet')),
                ('store', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_rating_set', to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuPickAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('outlink_a', models.URLField(blank=True, max_length=500, null=True)),
                ('outlink_b', models.URLField(blank=True, max_length=500, null=True)),
                ('pick_image_a', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
                ('pick_image_b', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
                ('chu_point_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_point_AB_a_set', to='pick.ChuPoint')),
                ('chu_point_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_point_AB_b_set', to='pick.ChuPoint')),
                ('pick_set', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_AB_set', to='pick.ChuPickSet')),
                ('store_a', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_AB_a_set', to='store.Store')),
                ('store_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_AB_b_set', to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
