# Generated by Django 2.1.9 on 2019-06-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_storepost_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuPickAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('pick_image_a', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
                ('pick_image_b', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuPickRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('pick_image', models.ImageField(blank=True, upload_to='pick/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuPickSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date', models.DateField(max_length=30, verbose_name='Section Published Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chupickrating',
            name='pick_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_rating_set', to='pick.ChuPickSet'),
        ),
        migrations.AddField(
            model_name='chupickrating',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_rating_set', to='store.Store'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='pick_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_AB_set', to='pick.ChuPickSet'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_AB_set', to='store.Store'),
        ),
    ]
