# Generated by Django 2.2.3 on 2019-07-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chupoint',
            name='tpo',
        ),
    ]
