# Generated by Django 2.1.9 on 2019-06-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategory_productcolor'),
        ('store', '0005_storepost_name'),
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Age')),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Primary_Style')),
                ('product_category', models.ManyToManyField(blank=True, related_name='product_category_set', to='product.ProductCategory')),
                ('product_color', models.ManyToManyField(blank=True, related_name='product_color_set', to='product.ProductColor')),
                ('secondary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Secondary_Style')),
                ('tpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Tpo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chupickab',
            name='store',
        ),
        migrations.AddField(
            model_name='chupickab',
            name='outlink_a',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='outlink_b',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='store_a',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_AB_a_set', to='store.Store'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='store_b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_A_b_set', to='store.Store'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chupickrating',
            name='outlink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chupickrating',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chupickrating',
            name='store',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_rating_set', to='store.Store'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='chu_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pick.ChuPoint'),
        ),
        migrations.AddField(
            model_name='chupickrating',
            name='chu_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pick.ChuPoint'),
        ),
    ]
