# Generated by Django 3.0.6 on 2020-07-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
        ('pick', '0002_auto_20200716_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks_on_primary_style', to='product.ProductStyle'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='product_color',
            field=models.ManyToManyField(blank=True, to='product.ProductColor'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='secondary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks_on_secondary_style', to='product.ProductStyle'),
        ),
        migrations.AlterField(
            model_name='pickabresult',
            name='selection',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], max_length=2, null=True),
        ),
    ]
