# Generated by Django 2.1.9 on 2019-06-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0002_auto_20190618_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chupickab',
            name='chu_point',
        ),
        migrations.AddField(
            model_name='chupickab',
            name='chu_point_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_point_AB_a_set', to='pick.ChuPoint'),
        ),
        migrations.AddField(
            model_name='chupickab',
            name='chu_point_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_point_AB_b_set', to='pick.ChuPoint'),
        ),
        migrations.AlterField(
            model_name='chupickab',
            name='pick_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_AB_set', to='pick.ChuPickSet'),
        ),
        migrations.AlterField(
            model_name='chupickab',
            name='store_b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_pick_AB_b_set', to='store.Store'),
        ),
        migrations.AlterField(
            model_name='chupickab',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chupickrating',
            name='pick_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_pick_rating_set', to='pick.ChuPickSet'),
        ),
        migrations.AlterField(
            model_name='chupickrating',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
