# Generated by Django 3.0.6 on 2020-07-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_store_validation_string'),
        ('product', '0096_auto_20200711_1155'),
        ('pick', '0003_auto_20200716_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Age'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks_on_primary_style', to='product.ProductStyle'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='secondary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks_on_secondary_style', to='product.ProductStyle'),
        ),
    ]
