# Generated by Django 3.0.8 on 2020-07-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20200719_0931'),
        ('pick', '0004_auto_20200716_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
