# Generated by Django 3.0.8 on 2020-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20200719_0931'),
        ('pick', '0006_pick_image_outlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='product_sub_category',
            field=models.ManyToManyField(blank=True, to='product.ProductSubCategory'),
        ),
    ]
