# Generated by Django 3.0.8 on 2020-07-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0007_pick_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickabresult',
            name='pick_A',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickAB_results_by_A', to='pick.Pick'),
        ),
        migrations.AddField(
            model_name='pickabresult',
            name='pick_B',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickAB_results_by_B', to='pick.Pick'),
        ),
        migrations.AlterField(
            model_name='pickabresult',
            name='pick_AB',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pick.PickAB'),
        ),
    ]
