# Generated by Django 3.0.8 on 2020-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0009_auto_20200728_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
