# Generated by Django 2.2.3 on 2019-07-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_auto_20190705_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Section Banner Title')),
                ('post_list', models.ManyToManyField(blank=True, related_name='post_set', to='store.StorePost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPagePublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name='Published Date')),
                ('main_section_post_group_list', models.ManyToManyField(blank=True, related_name='post_group_set', to='store.StorePost')),
                ('top_section_post_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.PostGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
