# Generated by Django 2.2.3 on 2019-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='ordering',
            field=models.IntegerField(default=999, null=True),
        ),
        migrations.AlterField(
            model_name='mainpagepublish',
            name='main_section_post_group_list',
            field=models.ManyToManyField(blank=True, related_name='post_group_set', to='publish.PostGroup'),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Post Group Title'),
        ),
    ]
