# Generated by Django 2.2.3 on 2019-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20190902_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='list_thumb_picture',
            field=models.ImageField(blank=True, upload_to='post-group-list-thumb/%Y/%m'),
        ),
    ]
