# Generated by Django 2.2.3 on 2019-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_postgroup_list_thumb_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkingBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordering', models.IntegerField(default=999, null=True)),
                ('title', models.CharField(max_length=50, verbose_name='Post Group Title')),
                ('list_thumb_picture', models.ImageField(blank=True, upload_to='post-group-list-thumb/%Y/%m')),
                ('cover_picture', models.ImageField(blank=True, upload_to='post-group-cover/%Y/%m')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
