# Generated by Django 2.2.3 on 2019-10-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_linkingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingbanner',
            name='published_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.BannerPublish'),
        ),
    ]
