# Generated by Django 2.2.3 on 2019-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0010_auto_20191004_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkingbanner',
            old_name='cover_picture',
            new_name='cover_picture_1',
        ),
        migrations.AddField(
            model_name='linkingbanner',
            name='cover_picture_2',
            field=models.ImageField(blank=True, upload_to='post-group-cover/%Y/%m'),
        ),
        migrations.AddField(
            model_name='linkingbanner',
            name='cover_picture_3',
            field=models.ImageField(blank=True, upload_to='post-group-cover/%Y/%m'),
        ),
        migrations.AddField(
            model_name='linkingbanner',
            name='cover_picture_4',
            field=models.ImageField(blank=True, upload_to='post-group-cover/%Y/%m'),
        ),
    ]
