# Generated by Django 2.2.3 on 2019-10-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20191001_0632'),
        ('publish', '0011_auto_20191004_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttaggroup',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store'),
        ),
    ]
