# Generated by Django 2.2.3 on 2019-10-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0012_posttaggroup_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttaggroup',
            options={'ordering': ('ordering',)},
        ),
    ]
