# Generated by Django 3.0.6 on 2020-05-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0013_auto_20191007_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingbanner',
            name='banner_type',
            field=models.CharField(choices=[('linking', 'LINKING'), ('base', 'BASIC'), ('coupon', 'COUPON')], default='base', max_length=20),
        ),
        migrations.AddField(
            model_name='linkingbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkingbanner',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
    ]
