# Generated by Django 3.0.6 on 2020-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0014_auto_20200525_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkingbanner',
            options={'ordering': ('-is_active', 'ordering')},
        ),
    ]
