# Generated by Django 3.0.6 on 2020-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0015_auto_20200525_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingbanner',
            name='coupon_code',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
