# Generated by Django 3.0.6 on 2020-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0016_linkingbanner_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkingbanner',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
