# Generated by Django 3.0.6 on 2020-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0017_auto_20200525_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingbanner',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='linkingbanner',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
