# Generated by Django 3.0.6 on 2020-06-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0018_auto_20200525_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerpublish',
            options={'verbose_name': '배너 발행 / Banner Publish', 'verbose_name_plural': '배너 발행 / Banner Publish'},
        ),
        migrations.AlterModelOptions(
            name='linkingbanner',
            options={'ordering': ('-is_active', 'ordering'), 'verbose_name': '배너 / Banner', 'verbose_name_plural': '배너 / Banner'},
        ),
        migrations.AlterModelOptions(
            name='mainpagepublish',
            options={'verbose_name': '홈 화면 발행 / Home Pulish', 'verbose_name_plural': '홈 화면 발행 / Home Pulish'},
        ),
        migrations.AlterModelOptions(
            name='postgroup',
            options={'ordering': ('ordering',), 'verbose_name': '상품 그룹 / Product Group', 'verbose_name_plural': '상품 그룹 / Product Group'},
        ),
        migrations.AlterModelOptions(
            name='posttaggroup',
            options={'ordering': ('ordering',), 'verbose_name': '상품 그룹 태그 / Product Group by Tag', 'verbose_name_plural': '상품 그룹 태그 / Product Group by Tag'},
        ),
    ]
