# Generated by Django 3.0.6 on 2020-07-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
        ('publish', '0019_auto_20200629_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttaggroup',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductPattern'),
        ),
    ]
