# Generated by Django 3.0.6 on 2020-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0020_posttaggroup_pattern'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(category=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_category_none'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(sub_category=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_sub_category_none'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(color=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_primary_style_none'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(style=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_style_none'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(pattern=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_pattern_none'),
        ),
        migrations.AddConstraint(
            model_name='posttaggroup',
            constraint=models.UniqueConstraint(condition=models.Q(store=None), fields=('category', 'sub_category', 'color', 'style', 'pattern', 'store'), name='pick_unique_with_everything_with_store_none'),
        ),
    ]
