# Generated by Django 3.0.6 on 2020-07-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0021_auto_20200716_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttaggroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
