# Generated by Django 3.0.6 on 2020-07-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
        ('store', '0052_store_validation_string'),
        ('publish', '0022_posttaggroup_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTagGroup',
            new_name='ProductTagGroup',
        ),
    ]
