# Generated by Django 3.0.9 on 2020-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0023_auto_20200716_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingbanner',
            name='data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linkingbanner',
            name='banner_type',
            field=models.CharField(choices=[('linking', 'LINKING'), ('base', 'BASIC'), ('coupon', 'COUPON'), ('navigation', 'NAVIGATION')], default='base', max_length=20),
        ),
    ]
