# Generated by Django 3.0.9 on 2020-09-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_auto_20200815_0822'),
        ('publish', '0024_auto_20200816_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='post_list',
        ),
        migrations.AddField(
            model_name='postgroup',
            name='product_list',
            field=models.ManyToManyField(blank=True, related_name='product_set', to='product.Product'),
        ),
    ]
