# Generated by Django 2.2.3 on 2019-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190705_0845'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidingbannersection',
            name='title_colored_keyword',
        ),
        migrations.RemoveField(
            model_name='slidingbannersection',
            name='title_foot',
        ),
        migrations.RemoveField(
            model_name='slidingbannersection',
            name='title_head',
        ),
        migrations.AddField(
            model_name='mainsection',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Main Section Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidingbannersection',
            name='post_list',
            field=models.ManyToManyField(blank=True, related_name='post_set', to='store.StorePost'),
        ),
        migrations.AddField(
            model_name='slidingbannersection',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Section Banner Title'),
            preserve_default=False,
        ),
    ]
