# Generated by Django 2.1.9 on 2019-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsection',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
