# Generated by Django 2.2.3 on 2019-07-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190705_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSection',
        ),
        migrations.DeleteModel(
            name='SlidingBannerSection',
        ),
    ]
