# Generated by Django 2.2.3 on 2019-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product Tag'),
        ),
    ]
