# Generated by Django 2.2.3 on 2019-08-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190730_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.StorePost'),
            preserve_default=False,
        ),
    ]
