# Generated by Django 2.2.3 on 2019-09-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190926_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ic_checked',
            field=models.BooleanField(default=False),
        ),
    ]
