# Generated by Django 2.2.6 on 2020-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLength',
            new_name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.ProductSize'),
        ),
    ]
