# Generated by Django 2.2.6 on 2020-04-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_product_thumb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_thumb_image',
        ),
        migrations.AddField(
            model_name='product',
            name='thumb_image_pk',
            field=models.IntegerField(default=1, verbose_name='Product Thumb Image'),
        ),
    ]
