# Generated by Django 2.2.6 on 2020-04-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200412_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_user',
        ),
        migrations.DeleteModel(
            name='UserFavoriteProduct',
        ),
    ]
