# Generated by Django 2.2.6 on 2020-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200412_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_image_type', models.CharField(choices=[('P', 'Picture'), ('V', 'Video')], max_length=25, null=True)),
                ('source', models.CharField(max_length=1024, null=True, verbose_name='URL Source')),
                ('source_thumb', models.CharField(max_length=1024, null=True, verbose_name='Thumb Small Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopeeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('liked_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('rating_star', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sleeve_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND')], default='VND', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free_ship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_source',
            field=models.CharField(choices=[('SHOPPEE', 'Shopee'), ('INSTAGRAM', 'Instagram'), ('HOMEPAGE', 'Homepage')], default='INSTAGRAM', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail_image',
            field=models.CharField(max_length=1024, null=True, verbose_name='Post Thumb Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StorePost'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
        migrations.DeleteModel(
            name='ProductSleeveLength',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_set', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='shopee_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ShopeeRating'),
        ),
    ]
