# Generated by Django 2.2.6 on 2020-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20200417_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('catid', models.IntegerField()),
                ('no_sub', models.BooleanField(default=False)),
                ('is_default_subcat', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
