# Generated by Django 2.2.6 on 2020-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_product_shopee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
