# Generated by Django 2.2.6 on 2020-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20200417_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='display_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
