# Generated by Django 2.2.6 on 2020-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20200417_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
