# Generated by Django 2.2.6 on 2020-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_product_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
