# Generated by Django 2.2.6 on 2020-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20200418_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extra_option',
            field=models.ManyToManyField(blank=True, to='product.ProductExtraOption'),
        ),
    ]
