# Generated by Django 2.2.6 on 2020-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20200418_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextraoption',
            name='source',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productextraoption',
            name='source_thumb',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
