# Generated by Django 2.2.6 on 2020-04-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20200418_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopee_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('VND', 'VND')], max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('shopee_sold_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
