# Generated by Django 2.2.6 on 2020-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextraoption',
            name='variation_groue',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
