# Generated by Django 2.2.6 on 2020-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_productoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextraoption',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
