# Generated by Django 2.2.6 on 2020-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20200418_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextraoption',
            name='variation_group',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
