# Generated by Django 2.2.6 on 2020-04-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_productextraoption_variation_groue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productextraoption',
            old_name='variation_groue',
            new_name='variation_group',
        ),
    ]
