# Generated by Django 2.2.6 on 2020-04-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_productextraoption_variation_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='name',
            new_name='display_name',
        ),
    ]
