# Generated by Django 2.2.6 on 2020-04-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20200418_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopeecategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='shopeecategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductSubCategory'),
        ),
    ]
