# Generated by Django 2.2.6 on 2020-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20200419_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopeecategory',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
