# Generated by Django 2.2.6 on 2020-04-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_shopeecategory_is_valid'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='productsubcategory',
            order_with_respect_to='category',
        ),
    ]
