# Generated by Django 2.2.6 on 2020-04-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20200419_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['category']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='productsubcategory',
            order_with_respect_to=None,
        ),
    ]
