# Generated by Django 2.2.6 on 2020-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_auto_20200420_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_review_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
