# Generated by Django 2.2.6 on 2020-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_product_current_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-product', 'ordering')},
        ),
        migrations.AddField(
            model_name='productimage',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
