# Generated by Django 2.2.6 on 2020-04-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20200423_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='ordering',
        ),
    ]
