# Generated by Django 2.2.6 on 2020-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_auto_20200423_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
