# Generated by Django 2.2.6 on 2020-04-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_auto_20200423_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopeerating',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopee_rating', to='product.Product'),
        ),
    ]
