# Generated by Django 2.2.6 on 2020-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_auto_20200428_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopeerating',
            name='shopee_1_star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopeerating',
            name='shopee_2_star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopeerating',
            name='shopee_3_star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopeerating',
            name='shopee_4_star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopeerating',
            name='shopee_5_star_count',
            field=models.IntegerField(default=0),
        ),
    ]
