# Generated by Django 2.2.6 on 2020-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_auto_20200429_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_product_backend_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Point'),
        ),
    ]
