# Generated by Django 2.2.6 on 2020-04-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_auto_20200429_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbackendrate',
            name='product_backend_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
