# Generated by Django 2.2.6 on 2020-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_auto_20200429_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_product_backend_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_review_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Review'),
        ),
    ]
