# Generated by Django 3.0.6 on 2020-05-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_auto_20200429_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['category', 'ordering']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
    ]
