# Generated by Django 3.0.6 on 2020-05-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20200514_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['current_product_backend_rating'], 'verbose_name': '제품', 'verbose_name_plural': '제품'},
        ),
    ]
