# Generated by Django 3.0.6 on 2020-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_auto_20200515_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND')], default='VND', max_length=20),
        ),
    ]
