# Generated by Django 3.0.6 on 2020-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_auto_20200516_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(default=0),
        ),
    ]
