# Generated by Django 3.0.6 on 2020-05-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_auto_20200520_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['-created_at', 'product'], 'verbose_name': '제품 옵션 / Product Option', 'verbose_name_plural': '제품 옵션 / Product Option'},
        ),
    ]
