# Generated by Django 3.0.6 on 2020-06-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20200601_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(default='Need to tranlate', max_length=255)),
            ],
            options={
                'verbose_name': '제품 패턴 / Product Tag',
                'verbose_name_plural': '제품 패턴 / Product Tag',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.ManyToManyField(blank=True, to='product.ProductPattern'),
        ),
    ]
