# Generated by Django 3.0.6 on 2020-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_auto_20200602_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpattern',
            options={'verbose_name': '제품 패턴 / Product Pattern', 'verbose_name_plural': '제품 패턴 / Product Pattern'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail_image',
            field=models.CharField(default='https://dabivn.com', max_length=1024, null=True),
        ),
    ]
