# Generated by Django 3.0.6 on 2020-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20200624_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
