# Generated by Django 3.0.6 on 2020-06-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_auto_20200625_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='view',
        ),
    ]
