# Generated by Django 3.0.6 on 2020-06-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_auto_20200625_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'current_product_backend_rating'], 'verbose_name': '제품', 'verbose_name_plural': '제품'},
        ),
    ]
