# Generated by Django 3.0.6 on 2020-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_auto_20200625_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
