# Generated by Django 3.0.6 on 2020-06-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_product_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductColor'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductSize'),
        ),
    ]
