# Generated by Django 3.0.6 on 2020-06-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_auto_20200629_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSourceExtraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_group', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('source_thumb', models.CharField(max_length=1024, null=True)),
                ('source', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': '제품 기타 옵션 / Product Extra Option',
                'verbose_name_plural': '제품 기타 옵션 / Product Extra Option',
            },
        ),
        migrations.AlterModelOptions(
            name='productextraoption',
            options={'verbose_name': '제품 기타 옵션 / Product Extra Option', 'verbose_name_plural': '제품 기타 옵션 / Product Extra Option'},
        ),
        migrations.AlterModelOptions(
            name='productstyle',
            options={'verbose_name': '제품 스타일 / Product Style', 'verbose_name_plural': '제품 스타일 / Product Style'},
        ),
        migrations.RemoveField(
            model_name='productextraoption',
            name='source',
        ),
        migrations.RemoveField(
            model_name='productextraoption',
            name='source_thumb',
        ),
        migrations.RemoveField(
            model_name='productextraoption',
            name='variation_group',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='shopee_sold_count',
        ),
        migrations.AddField(
            model_name='productextraoption',
            name='display_name',
            field=models.CharField(default='Need to tranlate', max_length=255),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='extra_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductExtraOption'),
        ),
        migrations.AlterField(
            model_name='productstyle',
            name='display_name',
            field=models.CharField(default='Need to tranlate', max_length=255),
        ),
        migrations.AlterField(
            model_name='productstyle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='source_extra_option',
            field=models.ManyToManyField(blank=True, to='product.ProductSourceExtraOption'),
        ),
    ]
