# Generated by Django 3.0.6 on 2020-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_auto_20200701_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
