# Generated by Django 3.0.6 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_auto_20200702_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='validation',
            field=models.CharField(choices=[('R', '확인 필요'), ('V', '확인 완료'), ('N', '비정상 상품')], default='R', max_length=255),
        ),
    ]
