# Generated by Django 3.0.6 on 2020-07-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_product_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_valid',
        ),
    ]
