# Generated by Django 3.0.6 on 2020-07-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_remove_product_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validation',
            field=models.CharField(choices=[('R', '확인 필요'), ('V', '확인 완료'), ('N', '비정상 상품'), ('D', '삭제 상품')], default='R', max_length=255),
        ),
    ]
