# Generated by Django 3.0.6 on 2020-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20200708_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='extra_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
