# Generated by Django 3.0.6 on 2020-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0092_auto_20200708_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['ordering', 'display_name'], 'verbose_name': '제품 색상 / Product Color', 'verbose_name_plural': '제품 색상 / Product Color'},
        ),
        migrations.AlterModelOptions(
            name='productpattern',
            options={'ordering': ['ordering', 'display_name'], 'verbose_name': '제품 패턴 / Product Pattern', 'verbose_name_plural': '제품 패턴 / Product Pattern'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['ordering', 'display_name'], 'verbose_name': '제품 사이즈 / Product Size', 'verbose_name_plural': '제품 사이즈 / Product Size'},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='productpattern',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='productsize',
            name='ordering',
            field=models.IntegerField(default=999),
        ),
    ]
