# Generated by Django 3.0.6 on 2020-07-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20200708_0618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'size', 'color', 'extra_option')},
        ),
    ]
