# Generated by Django 3.0.6 on 2020-07-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_auto_20200711_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color', 'extra_option'), name='unique_with_size_color'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(condition=models.Q(color=None), fields=('product', 'size', 'extra_option'), name='unique_without_color'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(condition=models.Q(size=None), fields=('product', 'color', 'extra_option'), name='unique_without_size'),
        ),
    ]
