# Generated by Django 3.0.6 on 2020-07-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20200711_1147'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(condition=models.Q(extra_option=None), fields=('product', 'color', 'size'), name='unique_without_extra'),
        ),
    ]
