# Generated by Django 3.0.6 on 2020-07-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='post_image_type',
            field=models.CharField(choices=[('P', 'Picture'), ('V', 'Video')], default='P', max_length=25, null=True),
        ),
    ]
