# Generated by Django 3.0.9 on 2020-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20200719_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='shipping_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
