# Generated by Django 3.0.9 on 2020-08-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0098_auto_20200815_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='shipping_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
