# Generated by Django 3.1.2 on 2020-10-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_auto_20200815_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validation',
            field=models.CharField(choices=[('R', 'Need to Review / 확인 필요'), ('V', 'Validated / 확인 완료'), ('N', 'Unqualified / 비정상 상품'), ('D', 'Deleted / 삭제 상품')], default='R', max_length=255),
        ),
    ]
