# Generated by Django 2.2.3 on 2019-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('ordering', models.IntegerField(null=True, verbose_name='Ordering')),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='StoreRecommendKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('ordering', models.IntegerField(null=True, verbose_name='Ordering Keyword')),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
