# Generated by Django 3.0.6 on 2020-05-15 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0067_auto_20200515_0721'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('VND', 'VND')], max_length=20)),
                ('is_free_ship', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('order-processing', '주문 완료'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('done', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불')], default='order-processing', max_length=50, verbose_name='주문상태')),
                ('is_active', models.BooleanField(default=False)),
                ('extra_message', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문서',
                'verbose_name_plural': '주문서',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('order-processing', '주문 완료'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('done', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불')], default='order-processing', max_length=50, verbose_name='주문상태')),
                ('delivery_status', models.CharField(max_length=50, verbose_name='배송상태')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order', verbose_name='주문서 상태')),
            ],
            options={
                'verbose_name': '주문서 상태 기록',
                'verbose_name_plural': '주문서 상태 기록',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('VND', 'VND')], max_length=20)),
                ('is_free_ship', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order', verbose_name='주문서')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '주문한 제품',
                'verbose_name_plural': '주문한 제품',
            },
        ),
    ]
