# Generated by Django 3.0.6 on 2020-05-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': '주문 제품', 'verbose_name_plural': '주문 제품'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'verbose_name': '주문 상태', 'verbose_name_plural': '주문 상태'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Tỉnh/Thành Phố'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Việt Nam', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=50, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(max_length=50, null=True, verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND')], default='VND', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND')], default='VND', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='배송상태'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order', verbose_name='주문'),
        ),
    ]
