# Generated by Django 3.0.6 on 2020-05-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_recipient'),
        ('order', '0002_auto_20200516_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ward',
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Recipient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
