# Generated by Django 3.0.6 on 2020-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200518_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipient',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Tỉnh/Thành Phố'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Việt Nam', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=50, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(max_length=50, null=True, verbose_name='Phường/Xã'),
        ),
    ]
