# Generated by Django 3.0.6 on 2020-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200518_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='cod', max_length=50, verbose_name='결제 방식'),
            preserve_default=False,
        ),
    ]
