# Generated by Django 3.0.6 on 2020-05-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200519_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
    ]
