# Generated by Django 3.0.6 on 2020-05-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_auto_20200522_1216'),
        ('order', '0010_auto_20200520_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['-created_at', 'order'], 'verbose_name': '주문 제품', 'verbose_name_plural': '주문 제품'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-created_at', 'order'], 'verbose_name': '주문 상태', 'verbose_name_plural': '주문 상태'},
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductOption', verbose_name='제품 옵션'),
        ),
    ]
