# Generated by Django 3.0.6 on 2020-05-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_auto_20200522_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('max_discount_price', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('valid_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
            },
        ),
        migrations.CreateModel(
            name='AppliedCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='order.Coupon', verbose_name='쿠폰')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupons', to='order.Order', verbose_name='주문')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '사용 쿠폰',
                'verbose_name_plural': '사용 쿠폰',
                'ordering': ['-is_active'],
            },
        ),
    ]
