# Generated by Django 3.0.6 on 2020-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_appliedcoupon_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimun_order_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('all', 'ALL')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='scope',
            field=models.CharField(choices=[('all', 'ALL')], default='all', max_length=50),
        ),
    ]
