# Generated by Django 3.0.6 on 2020-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200522_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scope',
        ),
        migrations.AddField(
            model_name='coupon',
            name='restriction',
            field=models.CharField(choices=[('none', 'NONE')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('total', 'TOTAL_PRICE'), ('shipping', 'SHIPPING'), ('product', 'PRODUCT')], default='total', max_length=50),
        ),
    ]
