# Generated by Django 3.0.6 on 2020-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200522_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedcoupon',
            options={'verbose_name': '사용 쿠폰', 'verbose_name_plural': '사용 쿠폰'},
        ),
        migrations.RemoveField(
            model_name='appliedcoupon',
            name='is_active',
        ),
    ]
