# Generated by Django 3.0.9 on 2020-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200805_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=500, verbose_name='배송상태'),
        ),
    ]
