# Generated by Django 3.0.9 on 2020-08-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200805_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'ordering': ['status_timestamp']},
        ),
    ]
