# Generated by Django 3.0.9 on 2020-08-13 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0025_auto_20200805_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order-processing', '주문 완료'), ('order-confirmed', '주문 확인'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('order-complete', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불'), ('refund-complete', '환불 완료'), ('change-complete', '교환 완료')], default='order-processing', max_length=50, verbose_name='주문상태'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order_status',
            field=models.CharField(choices=[('order-processing', '주문 완료'), ('order-confirmed', '주문 확인'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('order-complete', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불'), ('refund-complete', '환불 완료'), ('change-complete', '교환 완료')], default='order-processing', max_length=50, verbose_name='주문상태'),
        ),
        migrations.CreateModel(
            name='OrderGroupStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('order-processing', '주문 완료'), ('order-confirmed', '주문 확인'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('order-complete', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불'), ('refund-complete', '환불 완료'), ('change-complete', '교환 완료')], default='order-processing', max_length=50, verbose_name='주문상태')),
                ('ordered_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderedProduct', verbose_name='주문 제품')),
            ],
            options={
                'verbose_name': '주문 묶음 상태',
                'verbose_name_plural': '주문 묶음 상태',
                'ordering': ['-created_at', 'ordered_product'],
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('original_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('VND', 'VND')], default='VND', max_length=20)),
                ('is_free_ship', models.BooleanField(default=False)),
                ('shipping_price', models.IntegerField(default=0)),
                ('recipient_name', models.CharField(max_length=250, null=True)),
                ('contact_number', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(default='Việt Nam', max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Tỉnh/Thành Phố')),
                ('district', models.CharField(max_length=50, null=True, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=50, null=True, verbose_name='Phường/Xã')),
                ('additional_address', models.CharField(max_length=250, null=True, verbose_name='Địa chỉ cụ thể')),
                ('order_status', models.CharField(choices=[('order-processing', '주문 완료'), ('order-confirmed', '주문 확인'), ('delivery', '배송 중'), ('delivered', '배송 완료'), ('order-complete', '구매 완료'), ('cancelled', '주문 취소'), ('change-processing', '교환'), ('refund-processing', '환불'), ('refund-complete', '환불 완료'), ('change-complete', '교환 완료')], default='order-processing', max_length=50, verbose_name='주문상태')),
                ('payment', models.CharField(max_length=50, verbose_name='결제 방식')),
                ('extra_message', models.CharField(blank=True, max_length=255)),
                ('coupon_discounted', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=8)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문 그룹',
                'verbose_name_plural': '주문 그룹',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderGroup'),
        ),
    ]
