# Generated by Django 3.0.9 on 2020-08-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_storeaddress_is_active'),
        ('order', '0026_auto_20200813_0434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergroupstatuslog',
            options={'ordering': ['-created_at', 'ordered_product'], 'verbose_name': '주문 그룹 상태', 'verbose_name_plural': '주문 그룹 상태'},
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store'),
        ),
    ]
