# Generated by Django 2.1.8 on 2019-06-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Primary_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Primary Style')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Region Name')),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Secondary Style')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('insta_id', models.CharField(max_length=255, verbose_name='Instagram ID')),
                ('insta_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram URL')),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram Profile Image')),
                ('name', models.CharField(max_length=255, verbose_name='Instagram Name')),
                ('store_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ranking_changed', models.IntegerField(null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('follower', models.IntegerField(null=True, verbose_name='Instagram Follower')),
                ('following', models.IntegerField(null=True, verbose_name='Instagram Following')),
                ('post_num', models.IntegerField(null=True, verbose_name='Instagram Number of posts')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Instagram Description')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('shopee_url', models.URLField(blank=True, max_length=500, null=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Age')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Primary_Style')),
                ('region', models.ManyToManyField(blank=True, related_name='regions_set', to='store.Region')),
                ('secondary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Secondary_Style')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('post_like', models.IntegerField(null=True, verbose_name='Post Like')),
                ('post_comment', models.IntegerField(null=True, verbose_name='Post Comment')),
                ('post_taken_at_timestamp', models.IntegerField(null=True, verbose_name='Taken_at_timestamp')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Post Description')),
                ('post_image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Post Image')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tpo')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='tpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Tpo'),
        ),
    ]
