# Generated by Django 2.1.9 on 2019-06-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('post_total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('store_score', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('follower', models.IntegerField(null=True, verbose_name='Instagram Follower')),
                ('following', models.IntegerField(null=True, verbose_name='Instagram Following')),
                ('post_num', models.IntegerField(null=True, verbose_name='Instagram Number of posts')),
                ('ranking', models.IntegerField(null=True)),
                ('ranking_changed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25)),
                ('contact_status', models.CharField(choices=[('NONE', '연락안함'), ('DM', 'DM 보냄, 답장대기중'), ('CM', '연락중')], max_length=25)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Survey Content')),
                ('reaction_rate', models.IntegerField(blank=True, choices=[(1, '매우 부정적'), (2, '부정적'), (3, '의견 없음'), (4, '긍정적'), (5, '매우 긍정적')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='last_score',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ranking_changed',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_score',
        ),
        migrations.AddField(
            model_name='storepost',
            name='post_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='storepost',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_post_set', to='store.Store'),
        ),
        migrations.AddField(
            model_name='storesurvey',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_survey', to='store.Store'),
        ),
        migrations.AddField(
            model_name='storeranking',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_ranking_set', to='store.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='storeranking',
            unique_together={('date', 'store')},
        ),
    ]
