# Generated by Django 2.1.9 on 2019-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190607_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='current_ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='current_ranking_changed',
            field=models.IntegerField(null=True),
        ),
    ]
