# Generated by Django 2.2.3 on 2019-07-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190707_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categorys_set', to='store.Category'),
        ),
    ]
