# Generated by Django 2.1.9 on 2019-06-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0003_auto_20190607_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepost',
            name='main_section_published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_banner_post_set', to='product.MainSection'),
        ),
        migrations.AddField(
            model_name='storepost',
            name='ordering_keyword',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='storepost',
            name='sliding_section_published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliding_banner_post_set', to='product.SlidingBannerSection'),
        ),
    ]
