# Generated by Django 2.1.9 on 2019-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190614_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepost',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Name'),
        ),
    ]
