# Generated by Django 2.2.3 on 2019-07-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_productsize'),
        ('store', '0005_auto_20190722_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
