# Generated by Django 2.2.2 on 2019-06-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storepost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepost',
            name='post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
