# Generated by Django 2.2.2 on 2019-07-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storepost_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepost',
            name='post_image',
        ),
        migrations.AddField(
            model_name='storepost',
            name='type',
            field=models.CharField(choices=[('SP', 'Single Picture'), ('MP', 'Multiple Picture'), ('V', 'Video')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.URLField(null=True, verbose_name='URL Source')),
                ('store_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_video_set', to='store.StorePost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.URLField(null=True, verbose_name='URL Source')),
                ('source_thumb', models.URLField(null=True, verbose_name='Thumb Small Link')),
                ('store_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image_set', to='store.StorePost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
