# Generated by Django 2.2.3 on 2019-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_storepost_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='recent_post_1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='recent_post_2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='recent_post_3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
