# Generated by Django 2.2.2 on 2019-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190704_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storepost',
            old_name='type',
            new_name='post_type',
        ),
        migrations.AddField(
            model_name='storepost',
            name='post_id',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
