# Generated by Django 2.2.2 on 2019-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190704_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='source',
            field=models.CharField(max_length=1024, null=True, verbose_name='URL Source'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='source_thumb',
            field=models.CharField(max_length=1024, null=True, verbose_name='Thumb Small Link'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='source',
            field=models.CharField(max_length=1024, null=True, verbose_name='URL Source'),
        ),
    ]
