# Generated by Django 2.2.3 on 2019-08-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_is_new_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post_image_type',
            field=models.CharField(choices=[('P', 'Picture'), ('V', 'Video')], max_length=25, null=True),
        ),
    ]
