# Generated by Django 2.2.2 on 2019-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190704_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepost',
            name='post_thumb_image',
            field=models.CharField(max_length=1024, null=True, verbose_name='post_thumb_image'),
        ),
    ]
