# Generated by Django 2.2.2 on 2019-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storepost_post_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='view_count',
            field=models.IntegerField(null=True, verbose_name='Video View Count'),
        ),
    ]
