# Generated by Django 2.2.3 on 2019-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_postimage_post_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeranking',
            name='store_view_count',
            field=models.IntegerField(null=True, verbose_name='Store View Count of the day'),
        ),
    ]
