# Generated by Django 2.2.3 on 2019-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190826_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
