# Generated by Django 2.2.3 on 2019-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook_numeric_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
