# Generated by Django 2.2.3 on 2019-09-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_store_facebook_numeric_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepost',
            name='is_updated',
        ),
        migrations.AddField(
            model_name='storepost',
            name='is_product',
            field=models.BooleanField(default=True),
        ),
    ]
