# Generated by Django 2.2.3 on 2019-09-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20190930_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Age'),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Primary_Style'),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Secondary_Style'),
        ),
    ]
