# Generated by Django 2.2.6 on 2020-04-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200404_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereview',
            name='contact_number',
        ),
    ]
