# Generated by Django 2.2.6 on 2020-04-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_remove_storereview_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_stores', through='store.UserFavoriteStore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserStoreReview',
        ),
    ]
