# Generated by Django 2.2.6 on 2020-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200404_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='current_review_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='storeranking',
            name='review_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
