# Generated by Django 2.2.6 on 2020-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200404_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='X_axis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='Y_axis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
