# Generated by Django 2.2.6 on 2020-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200408_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeaddress',
            old_name='contact_number',
            new_name='google_map_url',
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
