# Generated by Django 2.2.6 on 2020-04-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('IF', 'Instagram Facebook'), ('IF(P)', 'Instagram Facebook with price info'), ('IH', 'Instagram Homepage'), ('IS', 'Instagram Shopee'), ('IFS', 'Instagram Facebook Shopee')], default='IF', max_length=25, null=True),
        ),
    ]
