# Generated by Django 2.2.6 on 2020-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200410_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('IF', 'INS FB'), ('IF(P)', 'INS FB w/P'), ('IH', 'INS HP'), ('IS', 'INS SHP'), ('IFS', 'INS FB SHP')], default='IF', max_length=25, null=True),
        ),
    ]
