# Generated by Django 2.2.6 on 2020-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200410_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='homepage_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
