# Generated by Django 2.2.6 on 2020-04-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_store_homepage_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreReview',
        ),
    ]
