# Generated by Django 2.2.6 on 2020-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_delete_storereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shopee_numeric_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
