# Generated by Django 2.2.6 on 2020-04-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_auto_20200423_2113'),
        ('store', '0036_auto_20200423_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductSubCategory'),
        ),
    ]
