# Generated by Django 2.2.6 on 2020-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_auto_20200423_2113'),
        ('store', '0037_store_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='store',
            name='product_category',
            field=models.ManyToManyField(blank=True, null=True, to='product.ProductCategory'),
        ),
    ]
