# Generated by Django 2.2.6 on 2020-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20200425_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
    ]
