# Generated by Django 3.0.6 on 2020-05-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20200425_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('IF', '-'), ('IF(P)', 'INS w/P'), ('IPFH', 'INS w/P HP'), ('IH', 'HP'), ('IS', 'Shopee'), ('IS(P)', 'Shopee w/P'), ('IFSH', 'Shopee HP'), ('IF(P)SH', 'INS w/P SH'), ('DS', 'Dosi-in')], default='IF', max_length=25, null=True),
        ),
    ]
