# Generated by Django 3.0.6 on 2020-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20200509_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('-is_active', 'current_ranking')},
        ),
    ]
