# Generated by Django 3.0.6 on 2020-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20200525_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dosiin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
