# Generated by Django 3.0.6 on 2020-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20200602_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_updated',
        ),
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
