# Generated by Django 3.0.6 on 2020-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20200625_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('IF', '-'), ('IF(P)', 'INS w/P'), ('IPFH', 'INS w/P HP'), ('IH', 'HP'), ('IS', 'Shopee'), ('IS(P)', 'Shopee w/P'), ('IFSH', 'Shopee HP'), ('IF(P)SH', 'INS w/P SH'), ('DS', 'Dosi-in'), ('PO', 'Preorder')], default='IF', max_length=25, null=True),
        ),
    ]
