# Generated by Django 3.0.6 on 2020-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20200702_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('IF', 'None'), ('IF(P)', 'Instagram'), ('IH', 'HP'), ('IS', 'Shopee'), ('DS', 'Dosi-in'), ('PO', 'Preorder')], default='IF', max_length=25, null=True),
        ),
    ]
