# Generated by Django 3.0.6 on 2020-07-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20200709_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('-is_active', 'current_ranking'), 'verbose_name': '스토어 / Store', 'verbose_name_plural': '스토어 / Store'},
        ),
    ]
