# Generated by Django 3.0.6 on 2020-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20200711_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='store/thumbnail', verbose_name='Instagram Profile Image'),
        ),
    ]
