# Generated by Django 3.0.6 on 2020-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_store_validation_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
