# Generated by Django 2.2.6 on 2020-04-23 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_product_current_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0035_store_shopee_numeric_id'),
        ('user', '0004_storereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreReview',
            new_name='ProductReview',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ImageField(blank=True, upload_to='review/%Y/%m')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_image_set', to='user.ProductReview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
