# Generated by Django 3.0.6 on 2020-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200423_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=250, null=True)),
                ('contact_number', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(default='Việt Nam', max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Tỉnh/Thành Phố')),
                ('district', models.CharField(max_length=50, null=True, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=50, null=True, verbose_name='Phường/Xã')),
                ('additional_address', models.CharField(max_length=250, null=True, verbose_name='Địa chỉ cụ thể')),
            ],
        ),
    ]
