# Generated by Django 3.0.6 on 2020-05-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200518_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['-primary']},
        ),
    ]
