# Generated by Django 3.0.6 on 2020-07-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20200519_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyleTaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lovely', models.IntegerField(default=0)),
                ('sexy', models.IntegerField(default=0)),
                ('simple', models.IntegerField(default=0)),
                ('street', models.IntegerField(default=0)),
                ('feminine', models.IntegerField(default=0)),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_style_tastes_on_primary_style', to='product.ProductStyle')),
                ('secondary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_style_tastes_on_secondary_style', to='product.ProductStyle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
