# Generated by Django 3.0.6 on 2020-07-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userproductview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductview',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
