# Generated by Django 3.0.6 on 2020-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userproductview_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductview',
            options={'verbose_name': '상품 뷰', 'verbose_name_plural': '상품 뷰'},
        ),
        migrations.AddConstraint(
            model_name='userproductview',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_with_product_user_for_userproductview'),
        ),
    ]
