# Generated by Django 3.0.6 on 2020-07-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0096_auto_20200711_1155'),
        ('user', '0014_auto_20200718_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoreView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스토어 뷰',
                'verbose_name_plural': '스토어 뷰',
            },
        ),
        migrations.AddConstraint(
            model_name='userstoreview',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_with_store_user_for_userstoreview'),
        ),
    ]
