# Generated by Django 3.0.6 on 2020-07-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_store_validation_string'),
        ('user', '0015_auto_20200718_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstoreview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
