# Generated by Django 3.0.6 on 2020-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200718_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductview',
            options={'ordering': ['-updated_at'], 'verbose_name': '상품 뷰', 'verbose_name_plural': '상품 뷰'},
        ),
        migrations.AlterModelOptions(
            name='userstoreview',
            options={'ordering': ['-updated_at'], 'verbose_name': '스토어 뷰', 'verbose_name_plural': '스토어 뷰'},
        ),
    ]
