# Generated by Django 3.0.6 on 2020-07-19 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0017_auto_20200718_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
