# Generated by Django 3.0.6 on 2020-07-19 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20200711_1155'),
        ('user', '0018_auto_20200719_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view_set', to='product.Product'),
        ),
    ]
