# Generated by Django 3.0.9 on 2020-08-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20200719_0931'),
        ('user', '0019_auto_20200719_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstyletaste',
            name='first_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_on_first_set', to='product.ProductColor'),
        ),
        migrations.AddField(
            model_name='userstyletaste',
            name='second_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_on_second_set', to='product.ProductColor'),
        ),
        migrations.AddField(
            model_name='userstyletaste',
            name='third_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_on_third_set', to='product.ProductColor'),
        ),
    ]
