# Generated by Django 2.2.6 on 2020-04-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191012_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
