# Generated by Django 2.2.6 on 2020-04-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0021_auto_20200410_0344'),
        ('core', '0010_userpushtoken_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_products', through='user.UserFavoriteProduct', to='product.Product'),
        ),
    ]
