# Generated by Django 2.2.6 on 2020-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_favorite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_product',
        ),
    ]
