# Generated by Django 2.2.6 on 2020-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200412_0800'),
        ('user', '0003_userfavoriteproduct'),
        ('core', '0012_remove_user_favorite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_products', through='user.UserFavoriteProduct', to='product.Product'),
        ),
    ]
