# Generated by Django 2.2.6 on 2020-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200412_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorite_users', through='user.UserFavoriteProduct', to='product.Product'),
        ),
    ]
