# Generated by Django 3.0.6 on 2020-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_information_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='information_status',
            field=models.CharField(choices=[('new', 'new'), ('basic', 'basic'), ('pick', 'pick'), ('done', 'done'), ('pass', 'pass')], default='new', max_length=100),
        ),
    ]
