# Generated by Django 3.0.6 on 2020-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200718_1031'),
        ('product', '0096_auto_20200711_1155'),
        ('core', '0020_auto_20200716_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_products',
            field=models.ManyToManyField(related_name='view_users', through='user.UserProductView', to='product.Product'),
        ),
    ]
