# Generated by Django 3.0.8 on 2020-07-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200730_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appleclienttoken',
            old_name='client_token',
            new_name='user_unique_id',
        ),
    ]
