# Generated by Django 3.0.8 on 2020-07-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
