# Generated by Django 3.0.8 on 2020-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_pushnotification_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='expiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
