# Generated by Django 3.0.8 on 2020-08-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200801_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_push', models.IntegerField(default=0)),
                ('success_push', models.IntegerField(default=0)),
                ('fail_push', models.IntegerField(default=0)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.PushNotification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
