# Generated by Django 3.0.8 on 2020-08-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200801_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-publish_date']},
        ),
    ]
