# Generated by Django 3.0.9 on 2020-08-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200730_1534'),
        ('notification', '0008_auto_20200802_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='push_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserPushToken'),
        ),
    ]
