# Generated by Django 3.0.9 on 2020-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20200830_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
