# Generated by Django 2.1.9 on 2019-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chupickabresult',
            name='pick_AB',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='chupickratingresult',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
